import Navbar from "@/components/Navbar";
import "./globals.css";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footer";
import type { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";
import { Toaster } from "react-hot-toast"

const roboto = Roboto({
  weight: ["100", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Coder's blog Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="container mx-auto flex flex-col h-screen">
        <Navbar />
        <main className="flex-1 overflow-y-auto mb-20 p-2 ">
          {children}
          <Toaster />
        </main>
        <Footer />
      </body>
      {/* <body className="container mx-auto">
        <Navbar />
        <main className="m-2 pb-32">{children}</main>
        <Footer />
      </body> */}
    </html>
  );
}
