import Navbar from '@/components/Navbar';
import './globals.css'
import { Roboto } from 'next/font/google'
import Footer from '@/components/Footer';
import type { Metadata } from 'next';
import NextNProgress from 'nextjs-progressbar';

const roboto = Roboto({
  weight: ['100','400','500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Coder's blog Homepage",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className='container mx-auto'>
        {/* <NextNProgress color="#53BD95"/> */}
        <Navbar />
        <main className='pb-32'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
